# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' Create a binned color palette function
#'
#' This function generates a binned color palette function that applies the 
#'    given palette function to the length of the input vector.
#'
#' @param palette Function. A function that generates a color palette.
#' @return A function that takes a vector `x` and returns a color palette of 
#'        the same length as `x`.
#' @noRd
#' @export
#' @examples
#' binned_pal()
binned_pal <- function(palette) {
  function(x) {
    palette(length(x))
  }
}
