# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' Generate a color palette function
#'
#' This function creates a color palette function based on the specified type, 
#' palette, and direction.
#' It supports qualitative palettes and allows customization of the maximum 
#' number of colors and their order.
#'
#' @param type Character. The type of palette. Default is "qualitative".
#' @param nmax Integer. The maximum number of colors. Default is NULL.
#' @param order Integer vector. The order of colors. Default is NULL.
#' @param palette Integer. The palette number. Default is 1.
#' @param direction Integer. The direction of the palette.
#'                  1 for normal, -1 for reversed. 
#'                  Default is 1.
#' @return A function that generates a color palette of length `n`.
#' @noRd
#' @export
#' @examples
#' #iom_pal_scale()
iom_pal_scale <- function(type = "qualitative",
                            nmax = NULL, order = NULL,
                            palette = 1, direction = 1) {
  pal <- iom_pal_name(palette, type)

  function(n) {
    if (is.null(nmax) | type != "qualitative") {
      nmax <- n
    }
    if (is.null(order) | type != "qualitative") {
      order <- 1:n
    }

    if (n > nmax) {
      warning("Insufficient values in scale_{color|fill}_iom_d. ",
        n, " needed but only ",
        nmax, " provided.",
        call. = FALSE
      )
    }

    # If <3 colors are requested, brewer.pal will return a 3-color palette and
    # give a warning. This warning isn't useful, so suppress it.
    # If the palette has k colors and >k colors are requested, brewer.pal will
    # return a k-color palette and give a warning. This warning is useful, so
    # don't suppress it.
    if (nmax < 3) {
      pal <- suppressWarnings(iom_pal(nmax, pal))
    } else {
      pal <- iom_pal(nmax, pal)
    }

    # In both cases ensure we have n items
    pal <- pal[order]

    if (direction == -1) {
      pal <- rev(pal)
    }

    unname(pal)
  }
}
