# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' IOM ggplot2 color scales
#' 
#' Color scales help differentiate between data points, making it easier to 
#' identify patterns, trends, and outliers.
#' 
#' You will need to select the right type of color scale depending on your data
#' 
#'  * Discrete Color Scales:scale_..._iom_d -  Use these when you have 
#'     categorical data  and that require a qualitative color palette. 
#'  * Continuous Color Scales: scale_..._iom_c -Use these for numerical data 
#'that progresses from low to high and that require a sequential color palette. 
#'  * Diverging Color Scales: scale_..._iom_b - Use these when you have data 
#'     with a meaningful midpoint and that require a diverging color palette.  
#'     
#'  depending on the geometry use, either fill or color - or a combination    
#'
#' @inheritParams scales::gradient_n_pal
#' @inheritParams ggplot2::continuous_scale
#' @inheritParams ggplot2::discrete_scale
#'
#' @param palette If a string, will use that named palette. 
#'    it can be any of the IOM brandied palettes: 
#'    -  2 qualitative palettes - `pal_iom` and `pal_iom_region`
#'    -  5 sequential palettes - `pal_blue`, `pal_navy`, `pal_green`,
#'                               `pal_red`, `pal_yellow`, `pal_grey`
#'    - 2 diverging palette - `pal_blue_red` & `pal_navy_rev`
#'    
#'    If a number, will
#'   index into the list of palettes of appropriate `type`
#' @param direction Sets the order of colors in the scale. If 1, the default,
#'   colors are as output by [iom_pal()]. If -1, the order of colors is reversed
#' @param nmax Maximum number of different colors the palette should contain. 
#'    If not provided, is calculated automatically
#'  from the data.
#' @param order Numeric vector listing the order in which the colors should be 
#'    used. Default is \code{1:nmax}.
#' @param ... Other arguments passed on to [discrete_scale()] or
#' [continuous_scale()] to control name, limits, breaks, labels and so forth
#'
#' @importFrom scales gradient_n_pal
#'
#' @return A discrete, continuous or binned `Scale` object
#'
#' @rdname iom_scale
#' @export
#' @examples
#' library(ggplot2)
#' library(iomthemes)
#'
#'
#' # Discrete Color Scales:scale_..._iom_d -  Use these when you have 
#' #     categorical data  and that require a qualitative color palette. 
#'
#' df <- data.frame(
#'   date = factor(rep(2010:2020, 2)),
#'   val = c(
#'     10.2, 10.2, 10.2, 11.5, 14,
#'     15.8, 17, 19.5, 20.5, 24.5, 20.6,
#'     4.9, 4.9, 4.9, 5.5, 5.5, 5.6,
#'     5.6, 5.7, 5.7, 5.8, 5.9
#'   ),
#'   set = rep(c("Set 1", "Set 2"), each = 11)
#' )
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title including 
#'               <span style='color:#0033A0;'>highlight color</span> | 2010-2020",
#'     subtitle = "My really subtitle that will cover more than one line and
#'               that will be automatically wrapped thanks to ggtext so I don't 
#'               have to manually put a line break",
#'     y = "values",
#'     caption = "Note: As it's HTML text the line break symbol is
#'                not '\\n'<br>Source: Dummy data"
#'   ) +
#'   scale_y_continuous(
#'     expand = expansion(c(0, 0.01))
#'   ) +
#'   scale_fill_iom_d() +
#'   theme_iom(
#'     grid = "Y",
#'     axis = "X",
#'     axis_title = "Y"
#'   )
#'
#' # Continuous Color Scales: scale_..._iom_c -Use these for numerical data that progresses
#' #  from low to high and that require a sequential color palette. 
#'
#' # Diverging Color Scales: scale_..._iom_b - Use these when you have data 
#' # 'with a meaningful midpoint and that require a diverging color palette. 
scale_color_iom_c <- function(..., 
                                palette = 1,
                                direction = 1,
                                na.value = "#E9E9E9", 
                                guide = "colourbar") {
  pal <- iom_pal_scale(
    type =  "sequential",
    palette = palette,
    direction = direction
  )(256)

  continuous_scale("colour",
    "iom_continuous",
    gradient_n_pal(pal),
    na.value = na.value,
    guide = guide,
    ...
  )
}

#' @rdname iom_scale
#' @export
scale_color_iom_d <- function(...,  
                                palette = 1,
                                direction = 1,
                                nmax = NULL,
                                order = NULL,
                                na.value = "#E9E9E9") {
  pal <- iom_pal_scale(
    type = "qualitative",
    palette = palette,
    nmax = nmax,
    order = order,
    direction = direction
  )

  discrete_scale("colour",
    "iom_discrete",
    pal,
    na.value = na.value,
    ...
  )
}

#' @rdname iom_scale
#' @export
scale_color_iom_b <- function(...,  
                                palette = 1,
                                direction = 1,
                                nmax = NULL,
                                order = NULL,
                                na.value = "#E9E9E9",
                                guide = "coloursteps") {
  pal <- binned_pal(iom_pal_scale(
    type = "qualitative",
    palette = palette,
    nmax = nmax,
    order = order,
    direction = direction
  ))

  binned_scale("colour",
    "iom_binned",
    pal,
    na.value = na.value,
    guide = guide,
    ...
  )
}

#' @rdname iom_scale
#' @aliases scale_color_iom_c
#' @export
scale_colour_iom_c <- scale_color_iom_c

#' @rdname iom_scale
#' @aliases scale_color_iom_d
#' @export
scale_colour_iom_d <- scale_color_iom_d

#' @rdname iom_scale
#' @aliases scale_color_iom_b
#' @export
scale_colour_iom_b <- scale_color_iom_b

#' @rdname iom_scale
#' @export
scale_fill_iom_c <- function(...,  
                               palette = 1,
                               direction = 1,
                               na.value = "#E9E9E9",
                               guide = "colourbar") {
  pal <- iom_pal_scale(
    type = "sequential",
    palette = palette,
    direction = direction
  )(256)

  continuous_scale("fill",
    "iom_continuous",
    gradient_n_pal(pal),
    na.value = na.value,
    guide = guide,
    ...
  )
}

#' @rdname iom_scale
#' @export
scale_fill_iom_d <- function(...,  
                               palette = 1,
                               direction = 1,
                               nmax = NULL,
                               order = NULL,
                               na.value = "#E9E9E9") {
  pal <- iom_pal_scale(
    type = "qualitative",
    palette = palette,
    nmax = nmax,
    order = order,
    direction = direction
  )

  discrete_scale("fill",
    "iom_discrete",
    pal,
    na.value = na.value,
    ...
  )
}

#' @rdname iom_scale
#' @export
scale_fill_iom_b <- function(...,  
                               palette = 1,
                               direction = 1,
                               nmax = NULL,
                               order = NULL,
                               na.value = "#E9E9E9",
                               guide = "coloursteps") {
  pal <- binned_pal(iom_pal_scale(
    type = "qualitative",
    palette = palette,
    nmax = nmax,
    order = order,
    direction = direction
  ))

  binned_scale("fill",
    "iom_binned",
    pal,
    na.value = na.value,
    guide = guide,
    ...
  )
}


