# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' IOM Color Palettes
#'
#' Creates a color palette from IOM branding.
#'
#' @param n Integer. Number of different colors in the palette. 
#'   Minimum depends on the palette (2),
#'  maximum depends on the palette (5, 7, or 10). 
#'  If `NULL`, the maximum number of colors for the palette is used.
#' @param name Character. A palette name from the IOM branding.
#' 
#'   we have:
#'    -  2 qualitative palettes - `pal_iom` and `pal_iom_region`
#'    -  5 sequential palettes - `pal_blue`, `pal_un`, `pal_green`,
#'                               `pal_red`, `pal_yellow`, `pal_grey`
#'    - 2 diverging palette - `pal_blue_red` & `pal_navy_rev`
#'   
#'             
#' 
#' @param ... Additional arguments passed to [grDevices::colorRampPalette].
#'
#' @return A character vector of hex color codes representing the palette.
#'
#' @details This function generates a color palette based on the specified
#'          IOM branding palette name.
#' If the number of colors `n` is not within the valid range for
#'     the palette, warnings are issued and the closest valid number of 
#'     colors is used.
#' @export
#' @examples
#' # Display all IOM color palette with filters
#'
#' # Qualitative Palette:
#' # When to Use: Use a qualitative palette when you have categorical data,
#' # meaning data that represents different groups or categories without any
#' # inherent order.
#' # Example: Different colors for different countries
#' iom_pal_display_all(type = "qualitative")
#' iom_pal(n =3, "pal_iom")
#'
#' # Sequential Palette:
#' # When to Use: Use a sequential palette when you have numerical data that
#' # progresses from low to high. This type of palette shows a gradient of 
#' # colors, usually from light to dark.
#' #Example: Temperature changes over a year, population density, or income levels.
#' iom_pal_display_all(n = 3, type = "sequential")
#' iom_pal_display_all(n = 5, type = "sequential")
#' iom_pal(3, "pal_blue")
#' iom_pal(5, "pal_un")
#' iom_pal(12, "pal_red")
#'
#' # Diverging Palette:
#' # When to Use: Use a diverging palette when you have numerical data with a 
#' # meaningful midpoint, such as zero, and you want to show variation on both 
#' # sides of this midpoint.
#' # Example: Anomalies (deviations from a norm),
#' # survey responses ranging from negative to positive.
#' # for diverging palette, you can not get more than 9 different colors
#' iom_pal_display_all(type = "diverging")
iom_pal <- function(n = NULL, name, ...) {
  # Check if the provided palette name is valid
  if (!(name %in% iomcolors$name)) {
    stop(paste(name, "is not a valid palette name\n"), call. = FALSE)
  }
  
  # Retrieve metadata for the selected palette
  selected_metadata <- iomcolors[iomcolors$name == name, ]
  min_n <- selected_metadata$min_n
  max_n <- selected_metadata$max_n
  type <- selected_metadata$type
  
  # Use the maximum number of colors if n is not specified
  if (is.null(n)) {
    n <- max_n
  }
  
  # Ensure the number of colors is within the valid range
  proper_n <- n
  if (proper_n > max_n) {
    proper_n <- max_n
  }
  
  # Issue warnings if the number of colors is not within the valid range for qualitative palettes
  if (!(n %in% min_n:max_n) && type == "qualitative") {
    warning(paste("Number of colors (n) in the", name, "palette should be between", min_n, "and", max_n, "\n"), call. = FALSE)
  }
  
  # Adjust the number of colors if it is below the minimum
  if (n < min_n) {
    warning(paste("Number of colors (n) in the", name, "palette should be between", min_n, "and", max_n, "\n"), call. = FALSE)
    proper_n <- min_n
    n <- min_n
  }
  
  # Retrieve the color codes for the specified number of colors
  coln <- paste0("n", proper_n)
  colors <- iomcolors[iomcolors$name == name, ][[coln]][[1]]
  
  # Generate a color ramp if more than 2 colors are requested
  if (n > 2) {
    colors <- grDevices::colorRampPalette(colors, ...)(n = n)
  }
  
  colors
}

