# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' IOM color palette viewer
#'
#' Displays a color palette from IOM brand color
#'
#' @param n Number of different colors in the palette, minimum depending on
#'    palette (2), maximum depending on palette (5, 7 or 10)
#' @param name A palette name
#'
#' @importFrom graphics image
#'
#' @return No return value, called for side effects
#'
#' @noRd
#'
#' @export
#' @examples
#' # Or select a specific one and limit the number of colors
#' iom_pal_display(3, "pal_iom")
iom_pal_display <- function(n = NULL, name) {
  selected_colors <- iom_pal(n, name)
  selected_type <- iomcolors[iomcolors$name == name, ][["type"]][[1]]
  image(1:n, 1, as.matrix(1:n),
    col = selected_colors,
    main = paste0(name, ": ", selected_type, " (", n, ")"),
    xlab = " ", ylab = " ", xaxt = "n", yaxt = "n", bty = "n"
  )
}
