# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' Retrieve the name of a color palette
#'
#' This function returns the name of a color palette based on the specified 
#'  palette number and type.
#'
#' @param palette Integer or character. The palette number or name.
#' @param type Character. The type of palette.
#' @return A character string representing the name of the color palette.
#' @noRd
#' @export
#' @examples
#' #iom_pal_name()
iom_pal_name <- function(palette, type) {
  if (is.character(palette)) {
    if (!palette %in% iomcolors$name) {
      warning("Unknown palette ", palette)
      palette <- "pal_blue"
    }
    return(palette)
  }
  type <- match.arg(type, unique(iomcolors$type))
  iomcolors$name[iomcolors$type == type][palette]
}
