# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' Check if Open Sans font is registered through \code{extrafont}
#'
#' Verify if Open Sans is registered through \code{extrafont}
#'
#' @importFrom systemfonts system_fonts
#' @importFrom extrafont fonts
#'
#' @returns TRUE if OpenSans is registered
#' @export
#' @noRd
#' @examples
#' package_font_registered()
package_font_registered <- function() {
  any(grepl("Open Sans", extrafont::fonts(), ignore.case = TRUE))
  suppressMessages(extrafont::loadfonts())
}
