# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' IOM [ggplot2] theme
#'
#' \code{theme_iom} provides a basic \bold{IOM} theme
#' to use in \bold{ggplot2} commands.
#'
#' @rdname theme_iom
#'
#' @param font_family Base font family `"Open Sans"`.
#' You need to have `"Open Sans"` font installed on your device in order to use it.
#' @param font_size Base font size in pt. Default to 12 pts.
#' @param plot_title_size Plot title font size. Default to `font_size` * 1.35.
#' @param plot_title_margin Plot title bottom margin. Default to `font_size`.
#' @param subtitle_size Plot subtitle font size. Default to `font_size`.
#' @param subtitle_margin Plot subtitle bottom margin. Default to `font_size` * 1.5.
#' @param strip_text_size Facet label font size. Default to `font_size` * 0.9.
#' @param strip_text_face Facet label font face. Default to "bold".
#' @param strip_text_just Facet label justification. Default to 0.
#' @param caption_size Caption font size. Default to `font_size` * 0.7.
#' @param caption_margin Caption top margin. Default to `font_size`.
#' @param axis_text Logical `TRUE`/`FALSE` or `xy`. Turn on and off axis label.
#' Use `x` or `y` to have only the correspondent active. Default to `TRUE`.
#' @param axis_text_size Axis label font size. Default to `font_size` * 0.9.
#' @param axis_title Logical `TRUE`/`FALSE` or `xy`. Turn on and off axis title.
#' Use `x` or `y` to have only the correspondent active. Default to `TRUE`.
#' @param axis_title_size Axis title font size. Default to `font_size` * 0.9.
#' @param axis Logical `TRUE`/`FALSE` or `xy`. Turn on and off axis.
#' Use `x` or `y` to have only the correspondent axis active. Don't forget to review
#' the `expand` argument of the `scale_x_*`/`scale_y_*` to avoid spacing between
#' the axis and the baseline of the plot. Default to `FALSE`.
#' @param axis_ticks Logical `TRUE`/`FALSE` or `xy`. Turn on and off axis ticks.
#' Use `x` or `y` to have only the correspondent axis ticks active. Default to `FALSE`.
#' @param grid Logical `TRUE`/`FALSE` or a combination of `X` or `x` and `Y` or y`.
#' Turn on and off panel grids. Use `X` or `Y` for major grids,
#' and `x` or `y` for minor grid.  Default to `XY`.
#' @param legend Logical `TRUE`/`FALSE`. Turn on and off the legend.
#' Default to `TRUE`.
#' @param legend_text_size Legend key font size. Default to `font_size` * 0.9.
#' @param legend_title Logical `TRUE`/`FALSE`. Turn on and off the legend title.
#' Default to `FALSE`.
#' @param legend_title_size Legend title font size. Default to `font_size` * 0.9.
#' @param plot_margin Plot margin (specify with `ggplot2::margin()`).
#' Default to `ggplot2::margin(font_size, font_size, font_size, font_size)`.
#' @param plot_background Plot background.
#' Put "transparent" for no background color. Default to "white".
#' @param void Logical `TRUE`/`FALSE`. If `TRUE`, all grid lines, ticks
#' and axes are removed. Default to `FALSE`.
#'
#' @return A ggplot2 theme object, the theme style.
#' @import ggplot2
#' @export
#' @examples
#' ## Usage
#'
#' #After loading the `{iomthemes}` package, you can apply the theme to 
#' # any `{ggplot2}` chart, by simply adding `theme_iom` at your call. 
#'
#' # For example:
#'
#' # Load packages
#' library(ggplot2)
#' library(iomthemes)
#'
#' # A dummy data frame
#' df <- data.frame(
#'   date = factor(rep(2010:2020, 2)),
#'   val = c(
#'     10.2, 10.2, 10.2, 11.5, 14,
#'     15.8, 17, 19.5, 20.5, 24.5, 20.6,
#'     4.9, 4.9, 4.9, 5.5, 5.5, 5.6,
#'     5.6, 5.7, 5.7, 5.8, 5.9
#'   ),
#'   set = rep(c("Set 1", "Set 2"), each = 11)
#' )
#'
#' # Base plot with theme_iom()
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title | 2010-2020",
#'     subtitle = "My subtitle",
#'     x = "date",
#'     y = "values",
#'     caption = "Source: Dummy data"
#'   ) +
#'   theme_iom()
#'
#' # The theme comes with some default settings, but you can customize most of it
#' #by adding parameters to the function call, as we will explore below.
#'
#' ## Grid
#'
#' # The `grid` parameter controls the display of both major and minor grid lines 
#' #in your plot. By default, major grid lines are visible and minor ones are hidden.
#' # 
#' # Using `grid = "XY"` adds both major X and Y grid lines, `grid = "X"` adds
#' # only major X grid lines, `grid = "Y"` adds only major Y grid lines, 
#' #and `grid = FALSE` removes all grid lines. 
#' # You can add minor grid lines by using lowercase `"xy"`, `"x"` or `"y"`. 
#'
#' #For example, let’s keep only the major Y grid lines:
#'  
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title | 2010-2020",
#'     subtitle = "My subtitle",
#'     x = "date",
#'     y = "values",
#'     caption = "Source: Dummy data"
#'   ) +
#'   theme_iom(
#'     grid = "Y" # Only major Y grid lines
#'   )
#'  
#'
#' # # Axis
#'
#' # Unsurprisingly, the axis represents the axis lines. However, it also includes
#' #different axis elements such as the axis title, axis text, and axis ticks.
#'
#' ### Axis lines
#'
#' #To control the visibility of axis lines, you can use the `axis` parameter 
#' # in the `theme_iom` function. By default, this parameter is set to `FALSE`,
#' # which turns off all the axis lines. Using `axis = "XY"` (or `axis = TRUE`)
#' # adds both X and Y axis, `axis = "X"` adds only the X axis, `axis = "Y"` 
#' #adds only the Y axis, and `axis = FALSE` removes all axis elements. 
#'
#' #For example, let's add only the X axis:
#'
#'  
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title | 2010-2020",
#'     subtitle = "My subtitle",
#'     x = "date",
#'     y = "values",
#'     caption = "Source: Dummy data"
#'   ) +
#'   theme_iom(
#'     grid = "Y",
#'     axis = "X" # Only X axis
#'   )
#'  
#' # Some space is missing! This is because `{ggplot2}` comes, by default, 
#' # with some expansion around the axis to create some room. 
#' # To remove this extra space, you can use the `expand` argument 
#' # in the `scale_x_*` or `scale_y_*` function.
#' # 
#' # **Modify the axis expansion:**
#' # 
#' # In this example, we will set the `expand` argument to `expansion(c(0, 0.01))` 
#' # for the y axis to remove the unwanted space, effectively “expanding” the axis
#' # by removing the space at the axis origin and adding a small padding 
#' # at the other end.
#'
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title | 2010-2020",
#'     subtitle = "My subtitle",
#'     x = "date",
#'     y = "values",
#'     caption = "Source: Dummy data"
#'   ) +
#'   scale_y_continuous(
#'     expand = expansion(c(0, 0.01)) # Remove axis expansion
#'   ) +
#'   theme_iom(
#'     grid = "Y",
#'     axis = "X"
#'   )
#'  
#'
#' ### Axis title and text
#'
#' #To control the visibility of axis titles and text, you can use the `axis_title`
#' # and `axis_text` parameters in the `theme_iom` function. By default, 
#' #these parameters are set to `TRUE`, which turns on all the axis titles and 
#' # text. Using `axis_title = FALSE` removes both X and Y axis titles,
#' # `axis_title = "X"` adds only the X axis title, `axis_title = "Y"` adds 
#' # only the Y axis title, and `axis_title = TRUE` adds all axis titles. 
#' # Similarly, `axis_text = TRUE` adds both X and Y axis text, `axis_text = "X"`
#' # adds only the X axis text, `axis_text = "Y"` adds only the Y axis text,
#' #and `axis_text = FALSE` removes all axis text. 
#'
#' #For example, let's keep only the Y axis title:
#'  
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title | 2010-2020",
#'     subtitle = "My subtitle",
#'     y = "values",
#'     caption = "Source: Dummy data"
#'   ) +
#'   scale_y_continuous(
#'     expand = expansion(c(0, 0.01))
#'   ) +
#'   theme_iom(
#'     grid = "Y",
#'     axis = "X",
#'     axis_title = "Y" # Only Y axis title
#'   )
#' #
#' ### Axis ticks
#'
#' #Axis ticks can sometimes be useful. To control the visibility of axis ticks,
#' # you can use the `axis_ticks` parameter in the `theme_iom` function.
#' # By default, this parameter is set to `FALSE`, which turns off all the 
#' # axis ticks. Using `axis_ticks = TRUE` adds both X and Y axis ticks, 
#' # `axis_ticks = "X"` adds only the X axis ticks, `axis_ticks = "Y"` adds only
#' # the Y axis ticks, and `axis_ticks = FALSE` removes all axis ticks.
#'
#' ## Text
#'
#' # Like all the chart elements, the different text elements, such as the 
#' # plot title, subtitle, caption, and more, can be controlled using the
#' # `theme_iom` function. We encourage you, not to touch any of these parameters,
#' # as they are part of IOM branding and should be used as is. 
#' # However, you can still adjust the font size, font family, margin or 
#' #justification of each of these elements using, for example,
#' #the `plot_title_size`, `plot_title_margin`, etc. parameters.
#'
#' #On top of the `theme_iom` parameters, the `{iomthemes}` package natively 
#' # incorporates the `{ggtext}` package for advanced text rendering in the title,
#' # subtitle and caption components. To showcase this, you can use the `{ggtext}` 
#' # functionalities to include styled text directly in your plots.
#'  
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     # Add some HTML style to the title
#'     title = "My title including
#'              <span style='color:#0033A0;'>highlight color</span> | 2010-2020",
#'     # Automatic wrapping of long text
#'     subtitle = "My really long subtitle that will cover more than one line and
#'                 that will be automatically wrapped thanks to ggtext so I don't
#'                 have to manually put a line break",
#'     y = "values",
#'     # Line break in the caption, use <br> instead of \n
#'     caption = "Note: As it's HTML text the line break symbol is not
#'                '\\n'<br>Source: Dummy data"
#'   ) +
#'   scale_y_continuous(
#'     expand = expansion(c(0, 0.01))
#'   ) +
#'   theme_iom(
#'     grid = "Y",
#'     axis = "X",
#'     axis_title = "Y"
#'   )
#'
#' ### Add text labels
#'
#' #Text labels added with `geom_text` will also display using the recommended 
#' # font and style.
#'  
#' ggplot(
#'   data = df,
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   # Add geom_text
#'   geom_text(aes(label = scales::number_format(accuracy = 0.1)(val)),
#'     position = position_stack(vjust = 0.5, reverse = TRUE),
#'     show.legend = FALSE
#'   ) +
#'   labs(
#'     title = "My title including
#'              <span style='color:#0033A0;'>highlight color</span> | 2010-2020",
#'     subtitle = "My really subtitle that will cover more than one line and that
#'                 will be automatically wrapped thanks to ggtext so I don't have 
#'                 to manually put a line break",
#'     y = "values",
#'     caption = "Note: As it's HTML text the line break symbol is
#'               not '\\n'<br>Source: Dummy data"
#'   ) +
#'   scale_y_continuous(
#'     expand = expansion(c(0, 0.01))
#'   ) +
#'   theme_iom(
#'     grid = "Y",
#'     axis = "X",
#'     axis_title = "Y"
#'   )
#'
#'
#' ## Void
#'
#' # To simplify the creation of pie/donut charts or maps, the `theme_iom` function
#' # comes with a `void` parameter. When set to `TRUE`, this parameter removes 
#' # all grid lines, ticks, and axes. For example, let's create a pie chart:
#'
#' ggplot(
#'   data = dplyr::filter(df, date == 2020),
#'   aes(x = date, y = val, fill = set)
#' ) +
#'   geom_col(
#'     position = position_stack(reverse = TRUE),
#'     width = 0.8
#'   ) +
#'   labs(
#'     title = "My title | 2020",
#'     subtitle = "My subtitle",
#'     y = "values",
#'     caption = "Source: Dummy data"
#'   ) +
#'   scale_fill_iom_d() +
#'   coord_polar(
#'     theta = "y",
#'     direction = -1
#'   ) +
#'   theme_iom(
#'     void = TRUE # Remove all grid lines, ticks, and axes
#'   )
#'
theme_iom <- function(
    font_family = if (package_font_installed()) "Open Sans" else "Arial",
    font_size = 12,
    plot_title_size = rel(1.35),
    plot_title_margin = font_size,
    subtitle_size = font_size,
    subtitle_margin = font_size * 1.5,
    strip_text_size = rel(0.9),
    strip_text_face = "bold",
    strip_text_just = 0,
    caption_size = rel(0.7),
    caption_margin = font_size,
    axis_text = TRUE,
    axis_text_size = rel(0.9),
    axis_title = TRUE,
    axis_title_size = rel(0.9),
    axis = FALSE,
    axis_ticks = FALSE,
    grid = "XY",
    legend = TRUE,
    legend_text_size = rel(0.9),
    legend_title = FALSE,
    legend_title_size = rel(0.9),
    plot_margin = margin(font_size, font_size, font_size, font_size),
    plot_background = "#ffffff",
    void = FALSE) {
  # colors
  dark_text <- "#1a1a1a"
  light_text <- "#666666"
  grid_col <- "#cccccc"

  # base theme override
  ret <- theme_minimal(base_family = font_family, base_size = font_size)

  ret <- ret + theme(text = element_text(
    family = font_family,
    color = dark_text
  ))

  # title
  ret <- ret + theme(plot.title = ggtext::element_textbox_simple(
    family = font_family,
    size = plot_title_size,
    face = "bold",
    color = "#000000",
    hjust = 0,
    lineheight = 1.2,
    margin = margin(0, 0, plot_title_margin, 0, "pt")
  ))
  ret <- ret + theme(plot.title.position = "plot")

  # subtitle
  ret <- ret + theme(plot.subtitle = ggtext::element_textbox_simple(
    family = font_family,
    size = subtitle_size,
    face = "plain",
    color = dark_text,
    hjust = 0,
    lineheight = 1.2,
    margin = margin(0, 0, subtitle_margin, 0, "pt")
  ))

  # strip
  ret <- ret + theme(strip.text = element_text(
    family = font_family,
    size = strip_text_size,
    face = strip_text_face,
    color = dark_text,
    hjust = strip_text_just
  ))

  # caption
  ret <- ret + theme(plot.caption = ggtext::element_textbox_simple(
    family = font_family,
    size = caption_size,
    face = "plain",
    color = light_text,
    hjust = 0,
    lineheight = 1.1,
    margin = margin(caption_margin, 0, 0, 0, "pt"),
  ))
  ret <- ret + theme(plot.caption.position = "plot")

  # axis text
  if (inherits(axis_text, "character") | axis_text == TRUE) {
    ret <- ret + theme(axis.text = element_text(
      size = axis_text_size,
      color = dark_text
    ))
    if (inherits(axis_text, "character")) {
      axis_text <- tolower(axis_text)
      if (regexpr("x", axis_text)[1] < 0) {
        ret <- ret + theme(axis.text.x = element_blank())
      } else {
        ret <- ret + theme(axis.text.x = element_text(
          size = axis_text_size,
          color = dark_text
        ))
      }
      if (regexpr("y", axis_text)[1] < 0) {
        ret <- ret + theme(axis.text.y = element_blank())
      } else {
        ret <- ret + theme(axis.text.y = element_text(
          size = axis_text_size,
          color = dark_text
        ))
      }
    } else {
      ret <- ret + theme(axis.text.x = element_text(
        size = axis_text_size,
        color = dark_text
      ))
      ret <- ret + theme(axis.text.y = element_text(
        size = axis_text_size,
        color = dark_text
      ))
    }
  } else {
    ret <- ret + theme(axis.text = element_blank())
  }

  # axis title
  if (inherits(axis_title, "character") | axis_title == TRUE) {
    ret <- ret + theme(axis.title = element_text(
      size = axis_title_size,
      color = light_text
    ))
    if (inherits(axis_title, "character")) {
      axis_title <- tolower(axis_title)
      if (regexpr("x", axis_title)[1] < 0) {
        ret <- ret + theme(axis.title.x = element_blank())
      } else {
        ret <- ret + theme(axis.title.x = element_text(
          size = axis_title_size,
          color = light_text
        ))
      }
      if (regexpr("y", axis_title)[1] < 0) {
        ret <- ret + theme(axis.title.y = element_blank())
      } else {
        ret <- ret + theme(axis.title.y = element_text(
          size = axis_title_size,
          color = light_text
        ))
      }
    } else {
      ret <- ret + theme(axis.title.x = element_text(
        size = axis_title_size,
        color = light_text
      ))
      ret <- ret + theme(axis.title.y = element_text(
        size = axis_title_size,
        color = light_text
      ))
    }
  } else {
    ret <- ret + theme(axis.title = element_blank())
  }

  # void
  if (void) {
    ret <- ret + theme(
      line = element_blank(),
      rect = element_blank(),
      axis.line = element_blank(),
      axis.line.x = NULL,
      axis.line.y = NULL,
      axis.text = element_blank(),
      axis.text.x = NULL,
      axis.text.x.top = NULL,
      axis.text.y = NULL,
      axis.text.y.right = NULL,
      axis.ticks = element_blank(),
      axis.ticks.length = grid::unit(0, "pt"),
      axis.title = element_blank(),
      axis.title.x = NULL,
      axis.title.x.top = NULL,
      axis.title.y = NULL,
      axis.title.y.right = NULL
    )
  } else {
    # axis line
    if (inherits(axis, "character") | axis == TRUE) {
      ret <- ret + theme(axis.line = element_line(
        color = dark_text,
        linewidth = rel(0.8)
      ))
      if (inherits(axis, "character")) {
        axis <- tolower(axis)
        if (regexpr("x", axis)[1] < 0) {
          ret <- ret + theme(axis.line.x = element_blank())
        } else {
          ret <- ret + theme(axis.line.x = element_line(
            color = dark_text
          ))
        }
        if (regexpr("y", axis)[1] < 0) {
          ret <- ret + theme(axis.line.y = element_blank())
        } else {
          ret <- ret + theme(axis.line.y = element_line(
            color = dark_text
          ))
        }
      } else {
        ret <- ret + theme(axis.line.x = element_line(
          color = dark_text
        ))
        ret <- ret + theme(axis.line.y = element_line(
          color = dark_text
        ))
      }
    } else {
      ret <- ret + theme(axis.line = element_blank())
    }

    # axis ticks
    if (inherits(axis_ticks, "character") | axis_ticks == TRUE) {
      ret <- ret + theme(axis.ticks.length = grid::unit(
        font_size / 2, "pt"
      ))
      ret <- ret + theme(axis.ticks = element_line(
        color = grid_col,
        linewidth = rel(.6)
      ))
      if (inherits(axis_ticks, "character")) {
        axis_ticks <- tolower(axis_ticks)
        if (regexpr("x", axis_ticks)[1] < 0) {
          ret <- ret + theme(axis.ticks.x = element_blank())
        } else {
          ret <- ret + theme(axis.ticks.x = element_line(
            color = grid_col
          ))
        }
        if (regexpr("y", axis_ticks)[1] < 0) {
          ret <- ret + theme(axis.ticks.y = element_blank())
        } else {
          ret <- ret + theme(axis.ticks.y = element_line(
            color = grid_col
          ))
        }
      } else {
        ret <- ret + theme(axis.ticks.x = element_line(
          color = grid_col
        ))
        ret <- ret + theme(axis.ticks.y = element_line(
          color = grid_col
        ))
      }
    } else {
      ret <- ret + theme(axis.ticks = element_blank())
    }

    # grid
    if (inherits(grid, "character") | grid == TRUE) {
      ret <- ret + theme(panel.grid = element_line(
        color = grid_col,
        linewidth = rel(.6)
      ))
      ret <- ret + theme(panel.grid.major = element_line(
        color = grid_col
      ))
      ret <- ret + theme(panel.grid.minor = element_line(
        color = grid_col
      ))

      if (inherits(grid, "character")) {
        if (regexpr("X", grid)[1] < 0) {
          ret <- ret + theme(panel.grid.major.x = element_blank())
        }
        if (regexpr("Y", grid)[1] < 0) {
          ret <- ret + theme(panel.grid.major.y = element_blank())
        }
        if (regexpr("x", grid)[1] < 0) {
          ret <- ret + theme(panel.grid.minor.x = element_blank())
        }
        if (regexpr("y", grid)[1] < 0) {
          ret <- ret + theme(panel.grid.minor.y = element_blank())
        }
      }
    } else {
      ret <- ret + theme(panel.grid = element_blank())
    }
  }

  # legend
  if (!legend) {
    ret <- ret + theme(legend.position = "none")
  } else {
    ret <- ret + theme(legend.text = element_text(
      size = legend_text_size,
      color = dark_text
    ))
    ret <- ret + theme(legend.position = "top")
    ret <- ret + theme(legend.justification = 0)
    if (!legend_title) {
      ret <- ret + theme(legend.title = element_blank())
    } else {
      ret <- ret + theme(legend.title = element_text(
        size = legend_title_size,
        color = dark_text,
        face = "bold"
      ))
    }
  }

  # tag
  ret <- ret + theme(plot.tag = element_text(
    size = font_size,
    color = "#0072bc",
    hjust = 0,
    vjust = 1
  ))
  ret <- ret + theme(plot.tag.position = c(0, 1))

  # margin
  ret <- ret + theme(plot.margin = plot_margin)

  # background
  ret <- ret + theme(plot.background = element_rect(
    fill = plot_background,
    color = plot_background
  ))

  ret
}



