# WARNING - Generated by {fusen} from dev/fusen_dev.Rmd: do not edit by hand

#' Update matching font defaults for text geoms
#'
#' Updates [ggplot2::geom_label] and [ggplot2::geom_text] font defaults
#' @importFrom ggrepel GeomTextRepel GeomLabelRepel
#'
#' @param family Font family, default "Lato".
#' @param face Font face, default "plain".
#' @param size font size in mm.
#' @param color Font color, default "#1a1a1a".
#'
#' @noRd
#' @export
#' @examples
#' update_geom_font_defaults()
update_geom_font_defaults <- function(
    family = if (package_font_installed()) "Open Sans" else "sans",
    face = "plain",
    size = 3.5,
    color = "#1a1a1a") {
  ggplot2::update_geom_defaults(
    "text",
    list(family = family, face = face, size = size, color = color)
  )
  ggplot2::update_geom_defaults(
    "label",
    list(family = family, face = face, size = size, color = color)
  )
  # ggplot2::update_geom_defaults(
  #   "text_repel",
  #   list(family = family, face = face, size = size, color = color)
  # )
  # ggplot2::update_geom_defaults(
  #   "label_repel",
  #   list(family = family, face = face, size = size, color = color)
  # )
}
